# This is a basic workflow to help you get started with Actions

name: SSH Remote Copy files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access itt
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Operations
      run: scp -i C:\Users\trbor\Downloads\POC_AWS.pem ec2-user@18.219.65.137:/home/ec2-user/GitHub_Actions/SubmissionDataForm-0.0.1-SNAPSHOT.jar D:\Actions
