# This is a basic workflow to help you get started with Actions

name: SSH Remote Copy files

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access itt
    - name: Checkout the code
      uses: actions/checkout@v2
      
    - name: Operations
      uses: alinz/ssh-scp-action@master
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        host: 3.140.249.25
        port: 22
        user: ec2-user
        # runs this on remove server
        ssh_before: |
         sudo su;

        # then downloads these 2 files
        scp: |
         scp -i C:\Users\trbor\Downloads\POC_AWS.pem ec2-user@3.140.249.25:/home/ec2-user/GitHub_Actions/SubmissionDataForm-0.0.1-SNAPSHOT.jar C:\Users\trbor\Downloads\

        # then run these commands
        ssh_after: |
          echo $HELLO
          echo $MESSAGE
          ls -lath
